# Generated by Django 4.2.4 on 2023-08-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='Task',
        ),
    ]
