# Generated by Django 4.2.4 on 2023-08-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_home_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2020-09-14'),
            preserve_default=False,
        ),
    ]
